### ISSUE TITLE
Segfault under complicated conditions

### ISSUE THREAD

**Issue by mlochbaum** [iocane/unbox#1]
The following code causes a segfault. If NOUN is assigned to a string not ending in `LF`, there is no segfault, and likewise if `NOUN` is assigned a value before assigning it a string ending in `LF`.

```
verb=: 0:`NOUN@.(0=#)
NOUN =: 'string',LF
verb ''
```

**Comment by iocane** [comment]
There is a bug for any pronoun inside of a gerund. 'string',LF just happens to be a magic bullet that causes a segfault. Other bit patterns get lucky and trigger an error. The fix is just a matter of finding the right place to put a missing check for gerund items that aren't functions. One extreme is to disallow unassigned names during gerund formation, but I don't think that is necessary.

**Comment by iocane** [comment]
Fixed in v0.1-rc1.
